start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/studypost/urls.py
from django.urls import path
from . import views
app_name= 'studypost'

urlpatterns = [
    path('notice/<int:id>', views.notice_home, name='notice_home'),
    path('notice_new/<int:id>', views.notice_new, name='notice_new'),
    path('notice_detail/<int:id>/', views.notice_detail, name='notice_detail'),
    path('notice_list/<int:id>/', views.notice_list, name='notice_list'),

    path('homework_new/<int:id>', views.homework_new, name='homework_new'),
    path('homework_detail/<int:id>/', views.homework_detail, name='homework_detail'),
    path('homework_list/<int:id>/', views.homework_list, name='homework_list'),
]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admin import views
from django.urls import path, include, re_path
from django.conf.urls.static import static



urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('study/', include('study.urls', namespace='study')),
    re_path(r'^accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/studypost/models.py
import re
from django.forms import ValidationError
from django.db import models
from django.urls import reverse
from study.models import Group



def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

class Notice(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    lnglat = models.CharField(max_length=50, blank=True,
                              validators=[lnglat_validator],
                              )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('studypost:notice_detail', args=[self.id])


class Homework(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, verbose_name='제목')
    content = models.TextField(verbose_name='내용')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('studypost:homework_detail', args=[self.id])

start/studypost/forms.py
from django import forms
from widgets.naver_map_point_widget import NaverMapPointWidget
from .models import Notice, Homework



class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = '__all__'
        exclude = ['group']
        widgets = {
            'lnglat': NaverMapPointWidget,
        }



class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        fields = '__all__'
        exclude = ['group']

start/studypost/views.py
from django.shortcuts import render, get_object_or_404, redirect
from study.models import Group, Membership
from .models import Notice, Homework
from .forms import NoticeForm, HomeworkForm

# Create your views here.


def notice_home(request, id):
    group = get_object_or_404(Group, id=id)
    return render(request, 'studypost/notice_home.html', {
        'group': group,
    })


def notice_new(request, id):
    group = Group.objects.get(id=id)
    if request.method == 'POST':
        form = NoticeForm(request.POST)
        if form.is_valid():
            r = request.POST
            notice = Notice.objects.create(group=group, title=r['title'], content=r['content'], lnglat=r['lnglat'])
            lng, lat = map(float, notice.lnglat.split(','))
            return render(request, 'studypost/notice_detail.html', {
                'notice': notice,
                'lng': lng,
                'lat': lat,
            })
    else:
        form = NoticeForm()
    return render(request, 'studypost/notice_new.html', {
        'form': form
    })



def notice_detail(request, id):
    notice = get_object_or_404(Notice, id=id)
    lng, lat = map(float, notice.lnglat.split(','))
    return render(request, 'studypost/notice_detail.html', {
        'notice': notice,
        'lng': lng,
        'lat': lat,
    })


def notice_list(request, id):
    group = Group.objects.get(id=id)
    ns = Notice.objects.filter(group=group)

    return render(request, 'studypost/notice_list.html', {
        'notice_list': ns,
    })


########################################################



def homework_new(request, id):
    group = Group.objects.get(id=id)
    if request.method == 'POST':
        form = HomeworkForm(request.POST)
        if form.is_valid():
            r = request.POST
            homework = Homework.objects.create(group=group, title=r['title'], content=r['content'])
            return redirect(homework)
    else:
        form = HomeworkForm()
    return render(request, 'studypost/homework_new.html', {
        'form': form
    })


def homework_detail(request, id):
    homework = get_object_or_404(Homework, id=id)

    return render(request, 'studypost/homework_detail.html', {
        'homework': homework,
    })


def homework_list(request, id):
    group = Group.objects.get(id=id)
    hs = Homework.objects.filter(group=group)

    return render(request, 'studypost/homework_list.html', {
        'homework_list': hs,
    })

start/studypost/templates/studypost/homework_detail.html
{% extends 'base.html' %}


{% block content %}

<h1>{{ homework.title }}</h1>

{{ homework.content|linebreaks }}

{% endblock %}

start/studypost/templates/studypost/homework_list.html
{% extends 'base.html' %}


{% block content %}

<table class="table table-hover table-bordered">
    <thead>
    <tr>
        <th>title</th>
        <th>content</th>
    </tr>
    </thead>
    <tbody>
    {% for homework in homework_list %}
    <tr>
        <td><a href="{% url "studypost:homework_detail" homework.id %}">{{ homework.title }}</a></td>
        <td>{{ homework.content }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

start/studypost/templates/studypost/homework_new.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

{% endblock %}

start/studypost/templates/studypost/notice_detail.html
{% extends 'base.html' %}


{% block content %}

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=d0vornngin&submodules=geocoder"></script>


<h1>{{ notice.title }}</h1>

{{ notice.content|linebreaks }}

{{ notice.created_at }}


<div id="map" style="width: 500px; height: 500px;">

</div>

<script>
    var base_position = new naver.maps.LatLng('{{ lat }}','{{ lng }}');
    var dom = document.getElementById('map');
    var map = new naver.maps.Map(dom, {
        center: base_position
    });
    var marker = new naver.maps.Marker({
        position: base_position,
        map: map
    });
    naver.maps.Event.addListener(map, 'click', function(e) {
        marker.setPosition(e.coord)
    });


    var infoWindow = new naver.maps.InfoWindow({
        anchorSkew: true,

        maxWidth: 200,
        backgroundColor: "#eee",
        borderWidth: 1,
        anchorColor: "#eee",
    });

    map.setCursor('pointer');


    function searchCoordinateToAddress(latlng) {

        infoWindow.close();

        naver.maps.Service.reverseGeocode({
            coords: latlng,
            orders: [
                naver.maps.Service.OrderType.ADDR,
                naver.maps.Service.OrderType.ROAD_ADDR
            ].join(',')
        }, function (status, response) {
            if (status === naver.maps.Service.Status.ERROR) {
                return alert('Something Wrong!');
            }

            var items = response.v2.results,
                address = '',
                htmlAddresses = [];

            for (var i = 0, ii = items.length, item, addrType; i < ii; i++) {
                item = items[i];
                address = makeAddress(item) || '';
                addrType = item.name === 'roadaddr' ? '[도로명 주소]' : '[지번 주소]';

                htmlAddresses.push((i + 1) + '. ' + addrType + ' ' + address);
            }

            infoWindow.setContent([
                '<div style="padding:10px;min-width:200px;line-height:150%;">',
                '<h4 style="margin-top:5px;">모임 장소</h4><br />',
                htmlAddresses.join('<br />'),
                '</div>'
            ].join('\n'));

            infoWindow.open(map, latlng);
        });
    }

    function initGeocoder() {
        map.addListener('click', function (e) {
            searchCoordinateToAddress(e.coord);
        });

        $('#address').on('keydown', function (e) {
            var keyCode = e.which;

            if (keyCode === 13) { // Enter Key
                searchAddressToCoordinate($('#address').val());
            }
        });

        $('#submit').on('click', function (e) {
            e.preventDefault();

            searchAddressToCoordinate($('#address').val());
        });

        var address = new naver.maps.LatLng('{{ lat }}','{{ lng }}');
        searchCoordinateToAddress(address);
    }

    function makeAddress(item) {
        if (!item) {
            return;
        }

        var name = item.name,
            region = item.region,
            land = item.land,
            isRoadAddress = name === 'roadaddr';

        var sido = '', sigugun = '', dongmyun = '', ri = '', rest = '';

        if (hasArea(region.area1)) {
            sido = region.area1.name;
        }

        if (hasArea(region.area2)) {
            sigugun = region.area2.name;
        }

        if (hasArea(region.area3)) {
            dongmyun = region.area3.name;
        }

        if (hasArea(region.area4)) {
            ri = region.area4.name;
        }

        if (land) {
            if (hasData(land.number1)) {
                if (hasData(land.type) && land.type === '2') {
                    rest += '산';
                }

                rest += land.number1;

                if (hasData(land.number2)) {
                    rest += ('-' + land.number2);
                }
            }

            if (isRoadAddress === true) {
                if (checkLastString(dongmyun, '면')) {
                    ri = land.name;
                } else {
                    dongmyun = land.name;
                    ri = '';
                }

                if (hasAddition(land.addition0)) {
                    rest += ' ' + land.addition0.value;
                }
            }
        }

        return [sido, sigugun, dongmyun, ri, rest].join(' ');
    }

    function hasArea(area) {
        return !!(area && area.name && area.name !== '');
    }

    function hasData(data) {
        return !!(data && data !== '');
    }

    function checkLastString(word, lastString) {
        return new RegExp(lastString + '$').test(word);
    }

    function hasAddition(addition) {
        return !!(addition && addition.value);
    }

    naver.maps.onJSContentLoaded = initGeocoder;
</script>


{% endblock %}

start/studypost/templates/studypost/notice_home.html
{% extends 'base.html' %}


{% block content %}

<div class="dropdown mt-3">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    공지 올리기
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="{% url "studypost:notice_new" group.id %}">모임 공지</a>
    <a class="dropdown-item" href="{% url "studypost:homework_new" group.id %}">과제 공지</a>
  </div>
</div>

<div>
    <a href="{% url "studypost:notice_list" group.id %}">모임 History</a>
    <a href="{% url "studypost:homework_list" group.id %}">과제 History</a>
</div>

{% endblock %}

start/studypost/templates/studypost/notice_list.html
{% extends 'base.html' %}


{% block content %}

<table class="table table-hover table-bordered">
    <thead>
    <tr>
        <th>title</th>
        <th>content</th>
    </tr>
    </thead>
    <tbody>
    {% for notice in notice_list %}
    <tr>
        <td><a href="{% url "studypost:notice_detail" notice.id %}">{{ notice.title }}</a></td>
        <td>{{ notice.content }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

start/studypost/templates/studypost/notice_new.html
{% extends 'base.html' %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

{% endblock %}