start/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login_form.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/revise', views.profile_revise, name='profile_revise'),
]

start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/study/urls.py
from django.urls import path
from . import views

app_name = 'study'
urlpatterns = [
    path('all_group_list/', views.all_group_list, name='all_group_list'),
    path('group_list/', views.group_list, name='group_list'),
    path('mystudy/', views.group_mystudy, name='mystudy'),
    path('new/', views.group_new, name='group_new'),
    path('<int:id>/', views.group_detail, name='group_detail'),
    path('<int:id>/settings', views.group_settings, name='group_settings'),
    path('<int:id>/mysettings', views.group_mysettings, name='group_mysettings'),
    path('register/<int:id>', views.group_register, name='group_register'),
    path('invitation/<int:invitation_url>/', views.group_registerbyurl, name='group_registerbyurl'),
    path('all_group_detail/<int:id>/', views.all_group_detail, name='all_group_detail'),
]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admin import views
from django.urls import path, include, re_path
from django.conf.urls.static import static



urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('study/', include('study.urls', namespace='study')),
    re_path(r'^accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/start/views.py
from django.shortcuts import redirect


def home(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    else:
        return redirect('study:mystudy')

start/start/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <style>
        a {
            text-decoration: None;
        }
    </style>
</head>
<body>
<header>
    {% if user.is_authenticated %}
        <div>
            <a href="{% url 'study:mystudy' %}"><h2>스터디 어드밋(study admit)</h2></a>
            <p>당신의 스터디를 관리해드리겠습니다</p>
        </div>
        <div style="background-color: antiquewhite; padding:1px; margin-top: 10px">

            {% if user.img_profile %}
                <div><img src="{{ user.img_profile.url }}" width="5%" height="5%"/></div>
            {% else %}
                <div><img src="{% static 'img/anonym.jpg' %}" width="5%" height="5%"/></div>
            {% endif %}

            <div>
                <p><strong>{{ user.nickname }}</strong>님 안녕하세요 </p>
                <a href="{% url "accounts:profile" %}"> 나의 프로필 </a>&nbsp; &nbsp;
                <a href="{% url "study:group_list" %}"> 나의 스터디 </a>&nbsp; &nbsp;
                <a href="{% url "accounts:logout" %}" onclick="return confirm('오늘 공부는 다 했나염?');">로그아웃</a>
            </div>
        </div>
    {% else %}
        <div>
            <a href="{% url 'home' %}"><h2>스터디 어드밋(study admit)</h2></a>
            <p>당신의 스터디를 관리해드리겠습니다</p>
        </div>
        <div></div>
    {% endif %}

    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-info mt-3" role="alert">
                    {{ message.message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

</header>
{% block content %}
{% endblock %}
</body>
</html>