start/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.UserCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login_form.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/revise', views.profile_revise, name='profile_revise'),
]

start/assignment/urls.py
from django.urls import path
from . import views

app_name = 'assignment'

urlpatterns = [
    path('<int:group_id>/', views.assignment_home, name='assignment_home'),
    path('<int:group_id>/list', views.assignment_list, name='assignment_list'),
    path('<int:group_id>/new/', views.assignment_new, name='assignment_new'),
    path('<int:assignment_id>/detail', views.assignment_detail, name='assignment_detail'),

    path('<int:assignment_id>/done_new/', views.done_new, name='done_new'),
    path('<int:done_id>/done_detail/', views.done_detail, name='done_detail'),
]

start/attendance/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

app_name = 'attendance'

urlpatterns = [
    path('<int:group_id>/', views.attend_list, name='attend_list'),
    path('<int:group_id>/detail/<int:detail_id>', views.attend_detail, name='attend_detail'),
    path('<int:group_id>/new/', views.attend_new, name='attend_new'),
    path('<int:group_id>/edit', views.attend_edit, name='attend_edit'),
]

start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/study/urls.py
from django.urls import path
from . import views

app_name = 'study'
urlpatterns = [
    path('all_group_list/', views.all_group_list, name='all_group_list'),
    path('group_list/', views.group_list, name='group_list'),
    path('mystudy/', views.group_mystudy, name='mystudy'),
    path('new/', views.group_new, name='group_new'),
    path('<int:id>/', views.group_detail, name='group_detail'),
    path('<int:id>/settings', views.group_settings, name='group_settings'),
    path('<int:id>/mysettings', views.group_mysettings, name='group_mysettings'),
    path('register/<int:id>', views.group_register, name='group_register'),
    path('invitation/<int:invitation_url>/', views.group_registerbyurl, name='group_registerbyurl'),
    path('all_group_detail/<int:id>/', views.all_group_detail, name='all_group_detail'),
]

start/studypost/urls.py
from django.urls import path
from . import views
app_name= 'studypost'

urlpatterns = [
    path('notice/<int:id>', views.notice_home, name='notice_home'),
    path('notice_new/<int:id>', views.notice_new, name='notice_new'),
    path('notice_detail/<int:id>/', views.notice_detail, name='notice_detail'),
    path('notice_list/<int:id>/', views.notice_list, name='notice_list'),

    path('homework_new/<int:id>', views.homework_new, name='homework_new'),
    path('homework_detail/<int:id>/', views.homework_detail, name='homework_detail'),
    path('homework_list/<int:id>/', views.homework_list, name='homework_list'),
]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admin import views
from django.urls import path, include, re_path
from django.conf.urls.static import static



urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('study/', include('study.urls', namespace='study')),
    re_path(r'^accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/study/forms.py
from django import forms
from .models import Group

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'group_code', 'group_bio', 'group_goal']
        labels = {
            'group_name': '',
            'group_code':'',
            'group_bio': '',
            'group_goal': '',
        }

class RegisterForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['group_code'].label = ''

    group_code = forms.CharField()

class GroupProfileForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'group_bio', 'group_goal']

        labels = {
            'group_name': '스터디이름',
            'group_bio': '스터디그룹 소개',
            'group_goal': '스터디 목표'
        }

        # help_texts = {}

start/study/views.py
from datetime import datetime, timezone, date, time
import functools
from random import randint

from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from accounts.forms import LoginForm
from accounts.models import StudyUser
from assignment.models import Assignment, Done, Injung_history
from attendance.views import attend_status_function

from attendance.forms import AttendConfirmForm
from attendance.views import sub_timedelta_function

from assignment.forms import DoneForm
from django.urls import reverse
from django.utils.html import format_html

from studypost.models import Notice
from .forms import GroupForm, RegisterForm, GroupProfileForm
from .models import Group, Membership, UpdateHistory
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from study.models import Membership


def group_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        usergroup_list = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
        if request.user.is_authenticated and group_name not in usergroup_list:
            return render(request, 'study/group_reject.html', {'group_name': group_name})
            # return HttpResponse("{}그룹 멤버가 아니므로 글을 쓸 수 없습니다.".format(group_name))

        return func(request, id)

    return wrapper


def mn_stf_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        membership = Membership.objects.get(group=group, person=user)
        if not membership.is_mn_stf or not membership.is_active:
            # return render(request, 'study/group_reject.html', {'group_name': group_name})
            return HttpResponse("매니저 권한이 필요합니다.")
        return func(request, id)

    return wrapper


def manager_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        membership = Membership.objects.get(group=group, person=user)
        if not membership.is_manager or not membership.is_active:
            # return render(request, 'study/group_reject.html', {'group_name': group_name})
            return HttpResponse("매니저 권한이 필요합니다.")
        return func(request, id)

    return wrapper


@login_required
def all_group_list(request):
    gs = Group.objects.all()
    g = request.GET.get('g', '')

    if g:
        gs = gs.filter(group_name__icontains=g)

    return render(request, 'study/all_group_list.html', {
        'all_group_list': gs,
    })


@login_required
def group_list(request):
    user = request.user
    # usergroup_list = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
    # group_list = Group.objects.filter(group_member=user)
    groups = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
    gs = Group.objects.filter(group_name__in=groups)
    g = request.GET.get('g', '')
    if g:
        gs = gs.filter(group_name__icontains=g)

    return render(request, 'study/group_list.html', {
        'group_list': gs,
    })


@login_required
def all_group_detail(request, id):
    group = get_object_or_404(Group, id=id)
    # membership_manager = [x.person for x in Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')]
    # membership_member = [x.person for x in Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')]

    membership_manager = Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')
    membership_staff = Membership.objects.filter(group=group, role='STAFF', status='ACTIVE')
    membership_member = Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')

    return render(request, 'study/all_group_detail.html', {
        'group': group,
        'membership_manager': membership_manager,
        'membership_staff': membership_staff,
        'membership_member': membership_member,
    })


@group_required
def group_detail(request, id):
    group = get_object_or_404(Group, id=id)
    user = request.user
    # membership = [x.person for x in Membership.objects.filter(group=group)]
    membership_manager = Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')
    membership_staff = Membership.objects.filter(group=group, role='STAFF', status='ACTIVE')
    membership_member = Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')
    usermembership = Membership.objects.get(group=group, person=user)

    memberships = Membership.objects.filter(group=group).order_by('-total_admit')
    penalty_list = Membership.objects.filter(group=group).order_by('-total_penalty')

    latest_update = UpdateHistory.objects.filter(group=group).order_by('created_at').last()
    attend_posts = group.attend_set.all().order_by('-pk')[:3]
    notice_posts = group.notice_set.all().order_by('-pk')[1:4]
    assign_posts = group.assignment_set.filter(group=group).order_by('-pk')[:3]

    for post in attend_posts:
        post.attend_status = attend_status_function(
            datetime.now(),
            post.init_datetime,
            post.gather_datetime,
            post.expired_datetime
        )
        post.save(update_fields=['attend_status'])

    now = datetime.now()

    latest_notice = Notice.objects.filter(group=group).order_by('created_at').last()

    # latest_assignment = "가장 최근 과제 instance"
    latest_assignment = Assignment.objects.filter(group=group).order_by('created_at').last()
    dones = Done.objects.filter(assignment=latest_assignment)
    authors = [x.author for x in dones]
    doneform = DoneForm()
    latest_attend = group.attend_set.all().order_by('pk').last()
    # "가장 최근 출석"
    attendform = AttendConfirmForm()

    try:
        confirm_value = latest_attend.attendconfirm_set.filter(
            attend_user=request.user.nickname,
            attend_check='출석 정보 없음'
        )
        # 출석 여부
        attendform = AttendConfirmForm()
        # "출석코드 입력해서 출석완료하는 form"
        # attend_history = "표로 이 출석에 대한 출석 결과 나옴"

        instances_attend = latest_attend.attendconfirm_set.filter(attend_check='출석').order_by('arrive_time')
        instances_late = latest_attend.attendconfirm_set.filter(attend_check='지각').order_by('arrive_time')
        instances_none = latest_attend.attendconfirm_set.filter(attend_check='출석 정보 없음')
        instances_absence = latest_attend.attendconfirm_set.filter(attend_check='결석')

    except:
        confirm_value = False
        instances_attend = False
        instances_late = False
        instances_none = False
        instances_absence = False

    context = {
        'membership_manager': membership_manager,
        'membership_staff': membership_staff,
        'membership_member': membership_member,
        'usermembership': usermembership,
        'group': group,
        'memberships_zip': zip(memberships, range(1, (len(memberships) + 1))),
        'penalty_list_zip': zip(penalty_list, range(1, (len(penalty_list) + 1))),
        'latest_update': latest_update,
        'attend_posts': attend_posts,
        'notice_posts': notice_posts,
        'assign_posts': assign_posts,

        'now': now,
        'latest_assignment': latest_assignment,
        'dones': dones,
        'doneform': doneform,
        'latest_attend': latest_attend,
        'confirm_value': confirm_value,
        'attendform': attendform,
        'authors': authors,

        'latest_notice':latest_notice,

        'instances_attend':instances_attend,
        'instances_late':instances_late,
        'instances_none':instances_none,
        'instances_absence':instances_absence,
    }

    if request.method == 'POST':
        if request.POST.get('assignment', ''):
            doneform = DoneForm(request.POST, request.FILES)
            if doneform.is_valid():
                done = doneform.save(commit=False)
                done.author = request.user
                done.assignment = latest_assignment
                done.index_in_assignment = len(Done.objects.filter(assignment=latest_assignment)) + 1
                done.save()
                return redirect('study:group_detail', id)


        elif request.POST.get('attendance', ''):
            attendform = AttendConfirmForm(request.POST)
            if attendform.is_valid():
                input_attend_number = attendform.cleaned_data['input_number']
                attend_number = latest_attend.attendance_number

                if attend_number == input_attend_number:

                    # 결석 인스턴스 가져오기
                    attending_member = latest_attend.attendconfirm_set.get(attend_user=request.user.nickname)

                    # 시간처리
                    state_time = latest_attend.gather_datetime
                    arrive_time = datetime.now()
                    sub_time_arrange = state_time - arrive_time
                    sub_time = sub_timedelta_function(sub_time_arrange)

                    # 지각, 출석 기록
                    if latest_attend.attend_status == '정상 출석 가능':
                        attending_member.arrive_time = arrive_time
                        attending_member.sub_time = sub_time
                        attending_member.attend_check = '출석'
                        attending_member.save()
                        usermembership.admit_attend += 1  # ㅇㅈ하나 추가
                        usermembership.total_admit += 1
                        usermembership.save()
                        messages.success(request, '성공적으로 출석했습니다!')

                        return redirect('study:group_detail', id)


                    elif latest_attend.attend_status == '지각 출석 가능':

start/study/templates/study/all_group_detail.html
{% extends 'base.html' %}

{% block content %}

<style>
    span{
        color: blue;
    }
</style>


<h1>Group <span>*{{group.group_name}}*</span> Details </h1>

<h3>구성원</h3>
<ol>
    {% for member in membership %}
    <li>{{ member.username }}</li>
    {% endfor %}
</ol>

<div>
    <a href="{% url "study:group_register" group.id %}">스터디 가입하기</a>
</div>

{% endblock %}

start/study/templates/study/all_group_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Group List</h1>

<div class="search_bar">
    <form action="" method="get">
        <input type="text" name="g" value="{{ g }}"/>
        <input type="submit" value="검색" class="btn btn-primary">
    </form>
</div>

{% for group in all_group_list %}
<tr>
    <td><a href="{% url "study:all_group_detail" group.id %}">{{group.group_name}}</a></td>
</tr>
{% endfor %}

{% endblock %}

start/study/templates/study/group_detail.html
{% extends 'group_base.html' %}

{% block content %}

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        span {
            color: blue;
        }
    </style>


    <h1>Group Details </h1>

    <div>
        <h4>초대 링크 :</h4>
        <input type="text" value="http://127.0.0.1:8000/study/invitation/{{ group.invitation_url }}" id="link"
               readonly/>
        <button onclick="myFunction()">초대 링크 복사</button>
    </div>
    <hr/>

    <div>
        <h4>구성원</h4>
        <ul style="list-style: none;">
            {% for member in membership_manager %}
                <li style="color:dodgerblue;">{{ member.person.nickname }}(관리자)</li>
                <a href="{% url 'study:member_info' member.id %}" class="btn btn-secondary">info</a>
            {% endfor %}
            {% for member in membership_staff %}
                <li style="color:deepskyblue;">{{ member.person.nickname }}(스탭)</li>
                <a href="{% url 'study:member_info' member.id %}" class="btn btn-secondary">info</a>
            {% endfor %}
            {% for member in membership_member %}
                <li>{{ member.person.nickname }}</li>
                <a href="{% url 'study:member_info' member.id %}" class="btn btn-secondary">info</a>
            {% endfor %}
            <li>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#invlinkModal">
                +
                </button>
            </li>
        </ul>
    </div>


<div class="modal fade" id="invlinkModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">링크로 새 멤버 초대하기</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>다른 회원이 링크를 통해 접속하면 그룹에 가입할 수 있습니다.
        </p>
        <input type="text" value="http://127.0.0.1:8000/study/invitation/{{ group.invitation_url }}" id="link"
               readonly/>
        <button onclick="myFunction()">초대 링크 복사</button>

      </div>

    </div>
  </div>
</div>


    <hr/>

    <div>
        <h4>그룹정보</h4><br/>
        <div>
            <div><h5>{{ group.group_name }} 그룹 소개</h5></div>
            <div>{{ group.group_bio }}</div>
        </div><br/>
        <div>
            <div><h5>우리의 목표</h5></div>
            <div>{{ group.group_goal }}</div>
        </div><br/>
        <div>
            <div><h5>이것만은 꼭 지키자!</h5></div>
            <div>{{ group.group_rule }}</div>
        </div><br/>
    </div>
    <hr/>

    <div>
        <div>
            <h4>{{ group.group_name }}의 현황</h4>
            <button type="button" onclick="location.href='{% url "study:group_update" group.id %}'">업데이트</button>
            <small>{{ latest_update.created_at }} 기준</small>
        </div>


        <div>
            <p><strong>ㅇㅈ 랭킹</strong></p>
            <table border="2" , style="text-align: center;">
                <tr style="text-align: center;">
                    <th>등수</th>
                    <th>닉네임</th>
                    <th>ㅇㅈ개수</th>
                </tr>
                {% for member, i in memberships_zip %}
                    <tr style="text-align: center;">
                        <td>{{ i }}등</td>
                        <td>{{ member.person.nickname }}</td>
                        <td>{{ member.total_admit }}개</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <br/>

        <div>
            <p><strong>벌금 현황</strong></p>

            <table border="2" , style="text-align: center">
                <tr style="text-align: center;">
                    <th>닉네임</th>
                    <th>지각</th>
                    <th>결석</th>
                    <th>과제 미제출</th>
                    <th>벌금</th>
                </tr>
                {% for member, i in penalty_list_zip %}
                    <tr style="text-align: center;">
                        <td>{{ member.person.nickname }}</td>
                        <td>{{ member.late_attend }}회</td>
                        <td>{{ member.noshow_attend }}회</td>
                        <td>{{ member.noshow_assign }}회</td>
                        <td>{{ member.total_penalty }}원</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <hr/>

    <div>
        <h4><a href="{% url 'studypost:notice_list' group.id %}">스터디 공지</a></h4>
        <div>
            {% for notice_post in notice_posts %}
                <br/>
                <div>
                    <div><a href="{% url "studypost:notice_detail" notice_post.id %}">{{ notice_post.title }}</a></div>
                    <div>게시일: {{ notice_post.created_at }}</div>
                    <div>글쓴이: {{ notice_post.author.nickname }}</div>
                </div>
                <br/>
            {% endfor %}
        </div>
    </div>
    <hr/>

    <div>
        <h4><a href="{% url 'attendance:attend_list' group.id %}">출석하기</a></h4>
        <div>
            {% for attend_post in attend_posts %}
                <br/>
                <div>
                    <div>
                        <a href="{% url 'attendance:attend_list' group.id %}">{{ attend_post.title }}</a>
                    </div>
                    <div>출석 가능 여부 : {{ attend_post.attend_status }}</div>
                    <div>출석 만료 시간 : {{ attend_post.expired_datetime }}</div>
                </div>
                <br/>
            {% endfor %}
        </div>
    </div>
    <hr/>

    <div>
        <h4><a href="{% url 'assignment:assignment_list' group.id %}">과제 인증하기</a></h4>
        <div>
            {% for assign_post in assign_posts %}
                <br/>
                <div>
                    <div><a href="{% url "assignment:assignment_detail" assign_post.id %}">{{ assign_post.title }}</a></div>
                    <div>{{ assign_post.due_date }} {% if assign_post.due_date <= now %}(만료){% endif %}</div>
                </div>
                <br/>
            {% endfor %}
        </div>
    </div>
    <hr/>

    <script>
        function myFunction() {
            var copyText = document.getElementById("link");
            copyText.select();
            document.execCommand("copy");
            alert("초대 링크를 복사했습니다." + copyText.value);
        }
    </script>

    <!--  alert("초대 링크를 복사했습니다." + copyText.value);-->

{% endblock %}

start/study/templates/study/group_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Group List</h1>

<div class="search_bar">
    <form action="" method="get">
        <input type="text" name="g" value="{{ g }}"/>
        <input type="submit" value="검색" class="btn btn-primary">
    </form>
</div>

{% for group in group_list %}
<tr>
    <td><a href="{% url "study:group_detail" group.id %}">{{group.group_name}}</a></td>
</tr>
{% endfor %}

{% endblock %}

start/study/templates/study/group_mysettings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ group.group_name }}의 내 설정

<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="out" value="out">
    <button onclick="return confirm('그룹을 탈퇴하면 재가입이 불가능하며, ' +
     '그룹페이지에 들어가 그룹과 관련된 내 정보를 열람할 수 없습니다. ' +
      '정말 탈퇴하겠습니까?');">그룹 탈퇴</button>
    </input>
</form>
</body>
</html>

start/study/templates/study/group_mystudy.html
{% extends 'base.html' %}

{% block content %}

    <br/>
    <div>
        <div><a href="{% url 'study:all_group_list' %}">스터디 찾기</a></div>
        <div><a href="{% url 'study:group_new' %}">스터디 만들기</a></div>
    </div>

{% endblock %}

start/study/templates/study/group_new.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

{% endblock %}

start/study/templates/study/group_register.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>
{% endblock %}

start/study/templates/study/group_registerbyurl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{{ group.group_name }}초대 링크입니다!

{% if not user.is_authenticated %}
    <p>그룹에 가입하려면 먼저 로그인해주세요.</p>
    <p style="color:red;">{{ error }}</p>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" name="login"/>
        </form>
    </div>

아직 스터디 어드밋 회원이 아니신가요?<a href="{% url 'accounts:signup' %}">회원가입</a>
<p>회원가입 후 다시 초대 링크로 접속해주세요.</p>
{% endif %}




<h4>현재 그룹 멤버</h4>

<ul style="list-style:none;">
    {% for member in membership %}
        <li>{{ member.person.username }} / {{ member.role }}</li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="register">
        <button>{{ group.group_name }}에 가입하기</button>
        </input>
    </form>
{% endif %}
</body>
</html>

start/study/templates/study/group_registerbyurl_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>이미 탈퇴/가입된 그룹입니다.</h3>
<a href="{% url "home" %}"><button>홈화면으로 돌아가기</button></a>
</body>
</html>

start/study/templates/study/group_reject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ group_name }}그룹 멤버가 아닙니다. {{ group_name }}그룹에 먼저 가입해주세요.
</body>
</html>

start/study/templates/study/group_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

매니저만 볼 수 있는 그룹 설정 페이지(그룹 프로필 설정, 권한 설정 등 기능 추가 예정)

</body>
</html>

start/study/templates/study/mystudy_list.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ user }}님의 스터디 리스트</h1>

    <ul>
    {% for group in groups %}
    <li>{{ group.group }}</li>
    {% endfor %}

    </ul>


{% endblock %}