start/assignment/urls.py
from django.urls import path
from . import views

app_name = 'assignment'

urlpatterns = [
    path('<int:group_id>/', views.assignment_home, name='assignment_home'),
    path('<int:group_id>/list', views.assignment_list, name='assignment_list'),
    path('<int:group_id>/new/', views.assignment_new, name='assignment_new'),
    path('<int:assignment_id>/detail', views.assignment_detail, name='assignment_detail'),

    path('<int:assignment_id>/done_new/', views.done_new, name='done_new'),
    path('<int:done_id>/done_detail/', views.done_detail, name='done_detail'),
]

start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.admin import views
from django.urls import path, include, re_path
from django.conf.urls.static import static



urlpatterns = [
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('study/', include('study.urls', namespace='study')),
    re_path(r'^accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/assignment/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from study.models import Group


class Assignment(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    index_in_group = models.IntegerField()
    title = models.CharField(max_length=30, verbose_name='과제명')
    content = models.TextField(verbose_name='내용')
    due_date = models.DateTimeField(verbose_name='기한')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('assignment:assignment_detail', args=[self.id])


class Done(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    index_in_assignment = models.IntegerField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    done_img = models.ImageField(upload_to='AssignmentsDone')
    injung = models.IntegerField(default=0)
    noinjung = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('assignment:done_detail', args=[self.id])

start/assignment/forms.py
from django import forms
from .models import Assignment, Done


class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = '__all__'
        exclude = ['created_at', 'group', 'index_in_group']


class DoneForm(forms.ModelForm):
    class Meta:
        model = Done
        fields = ('done_img',)

start/assignment/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from study.models import Group, Membership
from .models import Assignment, Done
from .forms import AssignmentForm, DoneForm


def assignment_home(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    assignment = Assignment.objects.filter(group=group).order_by('created_at').last()
    done = Done.objects.filter(assignment=assignment).order_by('created_at').last()
    return render(request, 'assignment/assignment_home.html', {
        'group': group, 'assignment': assignment, 'done': done,
    })


def assignment_list(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    assignments = Assignment.objects.filter(group=group).order_by('-created_at')
    num = len(assignments)
    return render(request, 'assignment/assignment_list.html', {
        'group': group, 'assignments': assignments, 'num': num,
    })


def assignment_new(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    if not Membership.objects.get(group=group, person=request.user).is_manager:
        messages.warning(request, '매니저만 과제를 등록할 수 있습니다.')
        return redirect('assignment:assignment_list', group_id)
    else:
        if request.method == 'POST':
            form = AssignmentForm(request.POST)
            if form.is_valid():
                assignment = form.save(commit=False)
                assignment.group = group
                assignment.index_in_group = len(Assignment.objects.filter(group=group))+1
                assignment.save()
                return redirect(assignment)
        else:
            form = AssignmentForm()
            return render(request, 'assignment/assignment_new.html', {'form': form})


def assignment_detail(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    dones = Done.objects.filter(assignment=assignment)
    authors = [x.author for x in dones]
    return render(request, 'assignment/assignment_detail.html', {
        'assignment': assignment, 'dones': dones, 'authors': authors, 'num': len(dones),
    })


def done_new(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    if request.method == 'POST':
        form = DoneForm(request.POST, request.FILES)
        if form.is_valid():
            done = form.save(commit=False)
            done.author = request.user
            done.assignment = assignment
            done.index_in_assignment = len(Done.objects.filter(assignment=assignment))+1
            done.save()
            return redirect(done)
    else:
        form = DoneForm()
    return render(request, 'assignment/done_new.html', {'form': form, 'assignment': assignment, })


def done_detail(request, done_id):
    done = get_object_or_404(Done, id=done_id)
    return render(request, 'assignment/done_detail.html', {
        'done': done,
    })

start/assignment/templates/assignment/assignment_detail.html
{% extends 'group_base.html' %}

{% block content %}

{{ message.message }}

    <div class="jumbotron">
    {% if membership.role != 'MEMBER' %}
        <a href="{% url "assignment:assignment_delete" assignment.id %}" class="btn btn-primary" style="float:right; margin-left: 2px">삭제</a>
        <a href="{% url "assignment:assignment_edit" assignment.id %}" class="btn btn-primary" style="float:right">수정</a>
    {% endif %}
    <h1 class="display-4">{{ assignment.title }}</h1>
        <p class="lead">{{ assignment.content|linebreaks }}</p>
        <p class="lead">{{ assignment.due_date }} 까지 {% if assignment.due_date <= now %}(기한 지남){% endif %}</p>
    <hr class="my-4">

        {% if user in authors %}
        <p>이미 인증하셨습니다! 멋져요~>_<</p>
        {% else %}
        <a href="{% url "assignment:done_new" assignment.id %}"
           class="btn btn-{% if assignment.due_date <= now %}secondary disabled{% else %}primary{% endif %}">인증하기</a>
        {% endif %}
    </div>


<h2>인증한 사람들 </h2>

{% if num == 0 %}
    <hr/>
    아무도 인증하지 않았어요 ㅠ_ㅠ
{% else %}
        <table class="table" >
            <thead>
                <tr align="center" style="border-top:2px solid #1976D2; border-bottom:2px solid #1976D2;">
                    <th scope="col">등수</th>
                    <th scope="col">이름</th>
                    <th scope="col">인증 시간</th>
                    <th scope="col">인정?</th>
                </tr>
            </thead>
            <tbody>
                {% for done in dones %}
                <tr align="center">
                    <th scope="row">{{ done.index_in_assignment }}등</th>
                    <td>{{ done.author }}</td>
                    <td>{{ done.created_at }}</td>
                    <td>{% if user != done.author %}
                            {% if user in done.injung_check %}
                                이미 ㅇㅈ함
                            {% else %}
                                <a href="{% url "assignment:done_detail" done.id %}" class="btn btn-primary">인정하러 가기</a>
                            {% endif %}
                        {% else %}
                            자추 ㄴㄴ
                        {% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{% endif %}

<br>

    <button type="button" class="btn btn-primary" style="float: right; margin-left: 2px" onclick="location.href='{% url "assignment:assignment_list" assignment.group.id %}'">목록으로</button>

   {% if usermembership.is_mn_stf %}
    <button type="button" class="btn btn-primary" style="float: right", onclick="location.href='{% url 'assignment:assignment_new' group.id%}' ">새 과제 등록</button>
    {% endif %}


    <!-- 과제 리스트 -->
    <div class="assignment_list" style="margin-top: 130px">
        <table class="table">
                <thead>
                    <tr align="center" style="border-top:3px solid #1976D2; border-bottom:3px solid #1976D2">
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증 여부</th>
                    </tr>
                </thead>
                <tbody>
                        {% for assign_ment in assignments %}
                    <tr {% if assign_ment == assignment %} style="background-color: rgba(25,118,210,0.1);"{% endif %} align="center">
                        <th scope="row">
                            {% if assign_ment == assignment %}
                                현재글
                            {% else %}
                                {{ assign_ment.index_in_group }}
                            {% endif %}</th>
                        <td><a href="{% url "assignment:assignment_detail" assign_ment.id %}">{{ assign_ment.title }}</a></td>
                        <td>{{ assign_ment.due_date }}{% if assign_ment.due_date <= now %}(만료){% endif %}</td>
                        <td>{% if user in assign_ment.submitters %}인증 완료{% else %}미인증{% endif %}</td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    </div>


{% endblock %}

start/assignment/templates/assignment/assignment_home.html
{% extends 'group_base.html' %}

{% block content %}
<h1>{{ group.group_name }}의 과제 현황 >_<</h1>

    {% if usermembership.is_mn_stf %}
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'assignment:assignment_new' group.id%}' ">새 과제 등록</button>
    {% endif %}

    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'assignment:assignment_list' group.id%}' ">새 인증 등록</button>
    <br/>

<h3>과제</h3>
    <button type="button" class="btn btn-primary" style="float: right" onclick="location.href='{% url 'assignment:assignment_list' group.id%}' ">목록으로</button>


{% if assignments == None %}
    등록된 과제 없음.
{% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">과제명</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증</th>
                    </tr>
                </thead>
                <tbody>
                    {% for assignment in assignments %}
                    <tr align="center">
                        <td><a href="{% url "assignment:assignment_detail" assignment.id %}">{{ assignment.title }}</a> </td>
                        <td>{{ assignment.due_date }}까지
                            {% if assignment.due_date <= now %}
                             (기한 지남)
                            {% endif %}</td>
                        <td>{% if user in assignment.submitters %}인증 완료
                            {% else %}
                            <a href="{% url "assignment:done_new" assignment.id %}"
                               class="btn btn-{% if assignment.due_date <= now %}secondary disabled{% else %}primary{% endif %}">인증하기</a>
                            {% endif %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

    <h3>인증</h3>     <button type="button" class="btn btn-primary" style="float: right" onclick="location.href='{% url 'assignment:done_list' group.id%}' ">목록으로</button>
    {% if dones == None %}
        등록된 인증 없음. 1빠 해볼까요~~?
    {% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">제목</th>
                        <th scope="col">이미지</th>
                        <th scope="col">인정?</th>
                    </tr>
                </thead>
                <tbody>
                        {% for done in dones %}
                            <tr align="center">
                    <th scope="row">{{ done.assignment.title }} 과제에 대한 <a href="{% url "assignment:done_detail" done.id %}">
                        <br>{{ done.author }}님의 인증</a></th>
                    <td><img src="{{ done.done_img.url }}" height="200"/></td>
                    <td>{% if user != done.author %}
                            {% if user in done.injung_check %}
                                이미 ㅇㅈ함
                            {% else %}
                                <a href="{% url "assignment:injung_plus" done.id %}" class="btn btn-primary">인정</a>
                            {% endif %}
                        {% else %}
                            자추 ㄴㄴ
                        {% endif %}</td>
                            </tr>
                        {% endfor %}
                </tbody>
            </table>
    {% endif %}
{% endif %}
{% endblock %}

start/assignment/templates/assignment/assignment_list.html
{% extends 'group_base.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message.message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% block content %}

<h1>{{ group.group_name }}의 과제 리스트</h1>


    <a href="{% url "assignment:assignment_home" group.id %}" class="btn btn-primary" style="float: right; margin-bottom: 5px; margin-left: 2px">과제 홈으로</a>


    {% if usermembership.is_mn_stf %}
    <a href="{% url 'assignment:assignment_new' group.id%}" class="btn btn-primary" style="float: right; margin-bottom: 5px;">새 과제 등록</a>
    {% endif %}


    {% if num == 0 %}
        <hr/>
        <p>등록된 과제가 없습니다.</p>
    {% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증</th>
                    </tr>
                </thead>
                <tbody>
                        {% for assignment in assignments %}
                    <tr align="center">
                        <th scope="row">{{ assignment.index_in_group }}</th>
                        <td><a href="{% url "assignment:assignment_detail" assignment.id %}">{{ assignment.title }}</a></td>
                        <td>{{ assignment.due_date }}{% if assignment.due_date <= now %}(만료){% endif %}</td>
                        <td>{% if user in assignment.submitters %}인증 완료
                            {% else %}
                            <a href="{% url "assignment:done_new" assignment.id %}"
                               class="btn btn-{% if assignment.due_date <= now %}secondary disabled{% else %}primary{% endif %}">인증하기</a>
                            {% endif %}</td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    {% endif %}
{% endblock %}

start/assignment/templates/assignment/assignment_new.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

start/assignment/templates/assignment/done_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ done.author }}님의 {{ done.assignment.title }} 과제 인증</h1>

<img src="{{ done.done_img.url }}" height="300"/>{{ done.created_at }} 에 인증!


<h3>인정? 노인정?</h3>

인정!: {{ done.injung }}
<br/>
노인정!: {{ done.noinjung }}

{% endblock %}

start/assignment/templates/assignment/done_new.html
{% extends 'group_base.html' %}

{% block content %}
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ assignment.title }} 과제 인증
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn btn-primary">제출</button>
</form>

{% endblock %}